
studios = (


('プレステージ', 'Prestige'),
('センタービレッジ', 'Center Village'),
('ながえスタイル', 'Nagae Style'),
('なでしこ', 'Nadeshiko'),
('FAプロ', 'FA Pro'),
('グローリークエスト', 'Glory Quest'),
('ケイ・エム・プロデュース', 'K M Produce'),
('タカラ映像', 'Takara Eizo'),
('マドンナ', 'MADONNA'),
('ルビー', 'Ruby'),
('ルーナ旬香舎', 'Luna Shunkosha'),
('小林興業', 'Kobayashi Kogyo'),
('溜池ゴロー', 'Tameike Goro'),
('熟撮/妄想族', 'Mosozoku'),
('キネマ座', 'Kinema'),
('DCollection', 'D*Collection'),
('Efupuro', 'FA Pro'),
('FAProPlatinum', 'FA Pro'),
('F&A', 'F & A'),
('Buiandoaarupurodakutsu', 'V&R PRODUCE'),
('FAPro', 'FA Pro'),
('GloryQuest', 'Glory Quest'),
('CenterVillage', 'Center Village'),
('CrystalEizo', 'Crystal Eizo'),
('CelebnoTomo', 'Celeb no Tomo'),
('MellowMoon', 'Mellow Moon'),
('TameikeGoro', 'Tameike Goro'),
('MaxA', 'Max A'),
('F&A', 'F & A'),
('DCollection', 'D*Collection'),
('Efupuro', 'FA Pro'),
('FAProPlatinum', 'FA Pro'),
('F&A', 'F & A'),
('Fujinsha/Emmanuelle', 'Emmanuelle'),
('Fujinsha / Emmanuelle', 'Emmanuelle'),
('GlobalMediaEntertainment', 'Global Media Entertainment'),
('TakaraEizo', 'Takara Eizo'),
('HotEntertainment', 'Hot Entertainment'),
('MarxBrothers', 'Marx Brothers'),
('MARX', 'Marx Brothers'),
('LADY*BABA / Emanuel', 'Emanuel'),
('TokyoOnko', 'Tokyo Onko'),
('S-CHANNEL/Mousouzoku', 'Mousouzoku'),
('KobayashiKogyo', 'Kobayashi Kogyo'),
('IdeaPocket', 'Idea Pocket'),
('ParadiseTV', 'Paradise TV'),
('IEnergy', 'Ienergy'),
('LahainaTokai', 'Lahaina Tokai'),
('NagaeStyle', 'Nagae Style'),
('S1NO.1Style', 'S1 NO.1 STYLE'),
('PlanetPlus', 'Planet Plus'),
('花と蜜', 'Flower & Honey'),
('KSB企画/エマニエル', 'Emmanuelle'),
('Academy', 'Academic'),
('DreamTicket', 'Dream Ticket'),
('FourDimension/Emmanuelle', 'Emmanuelle'),
('JukujoJAPAN/Emmanuelle', 'Emmanuelle'),
('YellowMoon（イエロームーン）', 'Yellow Moon'),
('ロイヤル', 'Royal'),
('SODクリエイト', 'SOD Create'),

)

genres = (

('お婆ちゃん', 'Grandma'),
('お風呂', 'Bath'),
('エマニエル', 'Emmanuelle'),
('旅行', 'Trip'),
('Big Tits Lover', 'Big Tits'),
('G*******g', 'Gang Bang'),

)

